version: '3.8'
networks:
  mysql:

services:
  mysql-5:
    image: mysql:5.7
    container_name: mysql-tls-1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_TLS_VERSION: "TLSv1"
    ports:
      - "13306:3306"
    networks:
      - mysql

